name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean __pycache__ and *.pyc
        run: find . -name "__pycache__" -exec rm -r {} + -o -name "*.pyc" -delete

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-book-theme sphinx-paramlinks sphinxcontrib-bibtex myst-parser importlib-resources
          pip install -e .

      - name: List structure
        run: |
          echo "Current directory structure:"
          ls -R

      - name: Create _static folder (if missing)
        run: mkdir -p docs/_static

      - name: Build documentation
        run: |
          cd docs
          make clean
          make html

      - name: Copy to gh-pages branch
        run: |
          mkdir -p docs/_build/html
          cp -r docs/_build/html/. .
          rm -rf docs  # clean up the source

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html